# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clipmill/shm/v1/shm.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'clipmill/shm/v1/shm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from clipmill.time.v1 import time_pb2 as clipmill_dot_time_dot_v1_dot_time__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63lipmill/shm/v1/shm.proto\x12\x0f\x63lipmill.shm.v1\x1a\x1b\x63lipmill/time/v1/time.proto\"\x9a\x02\n\x10\x42ufferDescriptor\x12\x19\n\x08shm_name\x18\x01 \x01(\tR\x07shmName\x12\x14\n\x05shape\x18\x02 \x03(\x04R\x05shape\x12/\n\x05\x64type\x18\x03 \x01(\x0e\x32\x19.clipmill.shm.v1.DataTypeR\x05\x64type\x12\x1e\n\ncolorspace\x18\x04 \x01(\tR\ncolorspace\x12\x36\n\x08timebase\x18\x05 \x01(\x0b\x32\x1a.clipmill.time.v1.TimebaseR\x08timebase\x12\x19\n\x08\x62yte_len\x18\x06 \x01(\x04R\x07\x62yteLen\x12\x16\n\x06sha256\x18\x07 \x01(\tR\x06sha256\x12\x19\n\x08lease_id\x18\x08 \x01(\tR\x07leaseId*\x83\x01\n\x08\x44\x61taType\x12\x19\n\x15\x44\x41TA_TYPE_UNSPECIFIED\x10\x00\x12\x10\n\x0c\x44\x41TA_TYPE_U8\x10\x01\x12\x11\n\rDATA_TYPE_I16\x10\x02\x12\x11\n\rDATA_TYPE_I32\x10\x03\x12\x11\n\rDATA_TYPE_F16\x10\x04\x12\x11\n\rDATA_TYPE_F32\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clipmill.shm.v1.shm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATATYPE']._serialized_start=361
  _globals['_DATATYPE']._serialized_end=492
  _globals['_BUFFERDESCRIPTOR']._serialized_start=76
  _globals['_BUFFERDESCRIPTOR']._serialized_end=358
# @@protoc_insertion_point(module_scope)
