#!/usr/bin/env node
/**
 * Compile tokens.json into the two CSS artifacts the shell consumes:
 *
 *   tokens.css   framework-agnostic custom properties, dark by default,
 *                overridden wholesale by :root[data-theme='light'].
 *   theme.css    the shadcn/ui semantic names (--background, --primary, …) as
 *                aliases onto those primitives, plus the Tailwind v4 @theme
 *                mapping, so the component library and the design system can
 *                never drift into two palettes.
 *
 * Both outputs are committed and re-checked in CI (decision R2): the generator
 * is the only writer, so a hand edit shows up as drift rather than surviving.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const PACKAGE_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PREFIX = '--cm';

/**
 * shadcn semantic name -> the --cm-* primitive it stands for.
 *
 * Surfaces map to glass rather than to opaque fills: a card in this design is a
 * blurred translucent layer, so `bg-card` has to resolve to the glass value or
 * every shadcn component would punch an opaque hole through the shell.
 */
const SHADCN_ALIASES = {
    background: 'bg-top',
    foreground: 'text-primary',
    card: 'glass',
    'card-foreground': 'text-primary',
    popover: 'glass-elevated',
    'popover-foreground': 'text-primary',
    primary: 'accent',
    secondary: 'glass-elevated',
    'secondary-foreground': 'text-primary',
    muted: 'recessed',
    'muted-foreground': 'text-muted',
    accent: 'accent-selected',
    'accent-foreground': 'text-primary',
    destructive: 'semantic-danger',
    border: 'glass-border',
    input: 'recessed-border',
    ring: 'accent-focus',
    // The sidebar is one continuous glass surface touching the viewport edges.
    sidebar: 'glass',
    'sidebar-foreground': 'text-secondary',
    'sidebar-primary': 'accent',
    'sidebar-accent': 'accent-selected',
    'sidebar-accent-foreground': 'text-primary',
    'sidebar-border': 'glass-border',
    'sidebar-ring': 'accent-focus',
    // Semantic states, kept on the design's reserved meanings.
    success: 'semantic-success',
    warning: 'semantic-warning',
    outbound: 'semantic-outbound',
};

/** Semantic names with no primitive behind them: text that sits on the accent. */
const SHADCN_LITERALS = {
    'primary-foreground': '#ffffff',
    'destructive-foreground': '#ffffff',
    'sidebar-primary-foreground': '#ffffff',
};

/** Groups that are identical in both themes and therefore emitted once. */
const SHARED_GROUPS = [
    'accent',
    'semantic',
    'font',
    'weight',
    'type',
    'radius',
    'control',
    'space',
    'shell',
    'blur',
];

class TokenSheetBuilder {
    #tokens;

    constructor(tokens) {
        this.#tokens = tokens;
    }

    /** `accent.default` collapses to `--cm-accent`; everything else is suffixed. */
    static #variableName(group, key) {
        return key === 'default' ? `${PREFIX}-${group}` : `${PREFIX}-${group}-${key}`;
    }

    static #declarations(entries, indent = '  ') {
        return entries.map(([name, value]) => `${indent}${name}: ${value};`).join('\n');
    }

    #sharedEntries() {
        const entries = [];
        for (const group of SHARED_GROUPS) {
            const values = this.#tokens[group];
            if (!values) {
                throw new Error(`tokens.json is missing the required group "${group}"`);
            }
            for (const [key, value] of Object.entries(values)) {
                entries.push([TokenSheetBuilder.#variableName(group, key), value]);
            }
        }
        return entries;
    }

    #themeEntries(theme) {
        const values = this.#tokens.themes[theme];
        if (!values) {
            throw new Error(`tokens.json is missing the "${theme}" theme`);
        }
        return Object.entries(values).map(([key, value]) => [`${PREFIX}-${key}`, value]);
    }

    /**
     * Dark lives on :root so the very first paint is dark even before the theme
     * script runs; light is a full override. The attribute always wins over the
     * OS preference, which is what makes a single in-app toggle authoritative.
     */
    buildTokensCss() {
        const { name, version, source } = this.#tokens.meta;
        return `/* ${name} v${version} — GENERATED by packages/tokens/scripts/build-css.mjs. Do not edit.
 * Source: ${source}
 */

:root {
${TokenSheetBuilder.#declarations(this.#sharedEntries())}

  /* Dark is the default theme. */
${TokenSheetBuilder.#declarations(this.#themeEntries('dark'))}

  color-scheme: dark;
}

:root[data-theme='light'] {
${TokenSheetBuilder.#declarations(this.#themeEntries('light'))}

  color-scheme: light;
}
`;
    }

    /**
     * shadcn/ui components are written against a fixed set of semantic variable
     * names (--background, --primary, --border, …). Rather than let that become
     * a second palette living alongside ours, every one of those names is an
     * alias for a --cm-* primitive.
     *
     * Aliases are emitted once, not per theme: `var()` resolves at use time, so
     * when the data-theme attribute swaps the primitive underneath, the semantic
     * name follows. One switch still drives the entire surface.
     */
    buildThemeCss() {
        const { name, version } = this.#tokens.meta;

        const aliases = Object.entries(SHADCN_ALIASES).map(([semantic, primitive]) => [
            `  --${semantic}`,
            `var(${PREFIX}-${primitive})`,
        ]);
        const literals = Object.entries(SHADCN_LITERALS).map(([semantic, value]) => [
            `  --${semantic}`,
            value,
        ]);
        const themeMappings = Object.keys(SHADCN_ALIASES)
            .concat(Object.keys(SHADCN_LITERALS))
            .map((semantic) => [`  --color-${semantic}`, `var(--${semantic})`]);

        return `/* ${name} v${version} shadcn semantic layer — GENERATED. Do not edit.
 * Each name below is an alias for a --cm-* primitive from tokens.css, so the
 * component library and the design system cannot drift into two palettes.
 */

:root {
${TokenSheetBuilder.#declarations(aliases, '')}
${TokenSheetBuilder.#declarations(literals, '')}

  /* shadcn derives sm/md/lg/xl from this; 12px yields 8px controls and 16px cards. */
  --radius: var(${PREFIX}-radius-panel);
}

@theme inline {
${TokenSheetBuilder.#declarations(themeMappings, '')}

  --font-sans: var(${PREFIX}-font-ui);
  --font-mono: var(${PREFIX}-font-mono);

${TokenSheetBuilder.#declarations(
    Object.keys(this.#tokens.type).map((key) => [`  --text-${key}`, `var(${PREFIX}-type-${key})`]),
    '',
)}

  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) + 4px);
}
`;
    }
}

const tokens = JSON.parse(readFileSync(join(PACKAGE_ROOT, 'src/tokens.json'), 'utf8'));
const builder = new TokenSheetBuilder(tokens);

const outputs = [
    ['tokens.css', builder.buildTokensCss()],
    ['theme.css', builder.buildThemeCss()],
];

const shouldCheck = process.argv.includes('--check');
let drifted = false;

for (const [filename, contents] of outputs) {
    const path = join(PACKAGE_ROOT, filename);
    if (shouldCheck) {
        let current = null;
        try {
            current = readFileSync(path, 'utf8');
        } catch {
            current = null;
        }
        if (current !== contents) {
            console.error(
                `tokens: ${filename} is out of date; run 'pnpm --filter @clipmill/tokens build'`,
            );
            drifted = true;
        }
    } else {
        writeFileSync(path, contents);
        console.log(`tokens: wrote ${filename}`);
    }
}

if (drifted) {
    process.exit(1);
}
if (shouldCheck) {
    console.log('tokens: OK (generated CSS matches tokens.json)');
}
