#!/usr/bin/env node
/**
 * Compile tokens.json into the two CSS artifacts the shell consumes:
 *
 *   tokens.css          framework-agnostic custom properties, dark by default,
 *                       overridden wholesale by :root[data-theme='light'].
 *   tailwind-preset.css Tailwind v4 @theme mapping so utilities resolve to the
 *                       same variables instead of duplicating literals.
 *
 * Both outputs are committed and re-checked in CI (decision R2): the generator
 * is the only writer, so a hand edit shows up as drift rather than surviving.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const PACKAGE_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PREFIX = '--cm';

/** Groups that are identical in both themes and therefore emitted once. */
const SHARED_GROUPS = [
    'accent',
    'semantic',
    'font',
    'weight',
    'type',
    'radius',
    'control',
    'space',
    'shell',
    'blur',
];

class TokenSheetBuilder {
    #tokens;

    constructor(tokens) {
        this.#tokens = tokens;
    }

    /** `accent.default` collapses to `--cm-accent`; everything else is suffixed. */
    static #variableName(group, key) {
        return key === 'default' ? `${PREFIX}-${group}` : `${PREFIX}-${group}-${key}`;
    }

    static #declarations(entries, indent = '  ') {
        return entries.map(([name, value]) => `${indent}${name}: ${value};`).join('\n');
    }

    #sharedEntries() {
        const entries = [];
        for (const group of SHARED_GROUPS) {
            const values = this.#tokens[group];
            if (!values) {
                throw new Error(`tokens.json is missing the required group "${group}"`);
            }
            for (const [key, value] of Object.entries(values)) {
                entries.push([TokenSheetBuilder.#variableName(group, key), value]);
            }
        }
        return entries;
    }

    #themeEntries(theme) {
        const values = this.#tokens.themes[theme];
        if (!values) {
            throw new Error(`tokens.json is missing the "${theme}" theme`);
        }
        return Object.entries(values).map(([key, value]) => [`${PREFIX}-${key}`, value]);
    }

    /**
     * Dark lives on :root so the very first paint is dark even before the theme
     * script runs; light is a full override. The attribute always wins over the
     * OS preference, which is what makes a single in-app toggle authoritative.
     */
    buildTokensCss() {
        const { name, version, source } = this.#tokens.meta;
        return `/* ${name} v${version} — GENERATED by packages/tokens/scripts/build-css.mjs. Do not edit.
 * Source: ${source}
 */

:root {
${TokenSheetBuilder.#declarations(this.#sharedEntries())}

  /* Dark is the default theme. */
${TokenSheetBuilder.#declarations(this.#themeEntries('dark'))}

  color-scheme: dark;
}

:root[data-theme='light'] {
${TokenSheetBuilder.#declarations(this.#themeEntries('light'))}

  color-scheme: light;
}
`;
    }

    buildTailwindPreset() {
        const { name, version } = this.#tokens.meta;
        const map = (entries, prefix) =>
            TokenSheetBuilder.#declarations(
                entries.map(([name_]) => [
                    `${prefix}-${name_.slice(PREFIX.length + 1)}`,
                    `var(${name_})`,
                ]),
            );

        // Theme-varying values are mapped from the dark key set: both themes
        // declare the same names, so either side yields an identical mapping.
        return `/* ${name} v${version} Tailwind v4 preset — GENERATED. Do not edit. */
@theme inline {
${map(
    this.#sharedEntries().filter(
        ([name_]) => name_.startsWith(`${PREFIX}-accent`) || name_.startsWith(`${PREFIX}-semantic`),
    ),
    '  --color',
)}
${map(this.#themeEntries('dark'), '  --color')}

  --font-ui: var(${PREFIX}-font-ui);
  --font-mono: var(${PREFIX}-font-mono);

${map(
    this.#sharedEntries().filter(([name_]) => name_.startsWith(`${PREFIX}-radius`)),
    '  --radius',
)}
}
`;
    }
}

const tokens = JSON.parse(readFileSync(join(PACKAGE_ROOT, 'src/tokens.json'), 'utf8'));
const builder = new TokenSheetBuilder(tokens);

const outputs = [
    ['tokens.css', builder.buildTokensCss()],
    ['tailwind-preset.css', builder.buildTailwindPreset()],
];

const shouldCheck = process.argv.includes('--check');
let drifted = false;

for (const [filename, contents] of outputs) {
    const path = join(PACKAGE_ROOT, filename);
    if (shouldCheck) {
        let current = null;
        try {
            current = readFileSync(path, 'utf8');
        } catch {
            current = null;
        }
        if (current !== contents) {
            console.error(
                `tokens: ${filename} is out of date; run 'pnpm --filter @clipmill/tokens build'`,
            );
            drifted = true;
        }
    } else {
        writeFileSync(path, contents);
        console.log(`tokens: wrote ${filename}`);
    }
}

if (drifted) {
    process.exit(1);
}
if (shouldCheck) {
    console.log('tokens: OK (generated CSS matches tokens.json)');
}
