#!/usr/bin/env node
/** Generate shared tokens, workspace palettes and component aliases. */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const PACKAGE_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PREFIX = '--cm';

/** Component aliases resolve against the active workspace palette. */
const SHADCN_ALIASES = {
    background: 'bg-top',
    foreground: 'text-primary',
    card: 'glass',
    'card-foreground': 'text-primary',
    popover: 'glass-elevated',
    'popover-foreground': 'text-primary',
    primary: 'accent',
    'primary-foreground': 'accent-foreground',
    secondary: 'glass-elevated',
    'secondary-foreground': 'text-primary',
    muted: 'recessed',
    'muted-foreground': 'text-muted',
    accent: 'accent-selected',
    'accent-foreground': 'text-primary',
    destructive: 'semantic-danger',
    border: 'glass-border',
    input: 'recessed-border',
    ring: 'accent-focus',
    sidebar: 'rail',
    'sidebar-foreground': 'text-secondary',
    'sidebar-primary': 'accent',
    'sidebar-primary-foreground': 'accent-foreground',
    'sidebar-accent': 'accent-selected',
    'sidebar-accent-foreground': 'text-primary',
    'sidebar-border': 'glass-border',
    'sidebar-ring': 'accent-focus',
    // Semantic states, kept on the design's reserved meanings.
    success: 'semantic-success',
    warning: 'semantic-warning',
    outbound: 'semantic-outbound',
};

/** Semantic names with no primitive behind them: text that sits on the accent. */
const SHADCN_LITERALS = {
    'destructive-foreground': '#ffffff',
};

/** Groups that are identical in both themes and therefore emitted once. */
const SHARED_GROUPS = [
    'accent',
    'semantic',
    'font',
    'weight',
    'type',
    'radius',
    'control',
    'space',
    'shell',
    'blur',
];

class TokenSheetBuilder {
    #tokens;
    #catalog;

    constructor(tokens, catalog) {
        this.#tokens = tokens;
        this.#catalog = catalog;
        if (!Object.hasOwn(catalog.themes, catalog.default)) {
            throw new Error('The default workspace theme is missing from the catalog');
        }
    }

    /** `accent.default` collapses to `--cm-accent`; everything else is suffixed. */
    static #variableName(group, key) {
        return key === 'default' ? `${PREFIX}-${group}` : `${PREFIX}-${group}-${key}`;
    }

    static #declarations(entries, indent = '  ') {
        return entries.map(([name, value]) => `${indent}${name}: ${value};`).join('\n');
    }

    #sharedEntries() {
        const entries = [];
        for (const group of SHARED_GROUPS) {
            const values = this.#tokens[group];
            if (!values) {
                throw new Error(`tokens.json is missing the required group "${group}"`);
            }
            for (const [key, value] of Object.entries(values)) {
                entries.push([TokenSheetBuilder.#variableName(group, key), value]);
            }
        }
        return entries;
    }

    #themeEntries(workspace, appearance) {
        const definition = this.#catalog.themes[workspace];
        const values = {
            ...this.#tokens.themes[appearance],
            ...definition.tokens,
            ...definition[appearance],
        };
        return Object.entries(values).map(([key, value]) => [`${PREFIX}-${key}`, value]);
    }

    buildTokensCss() {
        const { name, version, source } = this.#tokens.meta;
        const palettes = Object.keys(this.#catalog.themes).flatMap((workspace) =>
            ['dark', 'light'].map((appearance) => {
                const mode =
                    appearance === 'dark' ? ":not([data-theme='light'])" : "[data-theme='light']";
                return `:root[data-workspace-theme='${workspace}']${mode} {
${TokenSheetBuilder.#declarations(this.#themeEntries(workspace, appearance))}

  color-scheme: ${appearance};
}`;
            }),
        );
        return `/* ${name} v${version} — GENERATED by packages/tokens/scripts/build-css.mjs. Do not edit.
 * Sources: tokens.json, workspace-themes.json. See ${source}.
 */

:root {
${TokenSheetBuilder.#declarations(this.#sharedEntries())}

  /* Default workspace before preferences are restored. */
${TokenSheetBuilder.#declarations(this.#themeEntries(this.#catalog.default, 'dark'))}

  color-scheme: dark;
}

:root[data-theme='light'] {
${TokenSheetBuilder.#declarations(this.#themeEntries(this.#catalog.default, 'light'))}

  color-scheme: light;
}

${palettes.join('\n\n')}
`;
    }

    /**
     * shadcn/ui components are written against a fixed set of semantic variable
     * names (--background, --primary, --border, …). Rather than let that become
     * a second palette living alongside ours, every one of those names is an
     * alias for a --cm-* primitive.
     *
     * Aliases are emitted once, not per theme: `var()` resolves at use time, so
     * when the data-theme attribute swaps the primitive underneath, the semantic
     * name follows. One switch still drives the entire surface.
     */
    buildThemeCss() {
        const { name, version } = this.#tokens.meta;

        const aliases = Object.entries(SHADCN_ALIASES).map(([semantic, primitive]) => [
            `  --${semantic}`,
            `var(${PREFIX}-${primitive})`,
        ]);
        const literals = Object.entries(SHADCN_LITERALS).map(([semantic, value]) => [
            `  --${semantic}`,
            value,
        ]);
        const themeMappings = Object.keys(SHADCN_ALIASES)
            .concat(Object.keys(SHADCN_LITERALS))
            .map((semantic) => [`  --color-${semantic}`, `var(--${semantic})`]);

        return `/* ${name} v${version} shadcn semantic layer — GENERATED. Do not edit.
 * Each name below is an alias for a --cm-* primitive from tokens.css, so the
 * component library and the design system cannot drift into two palettes.
 */

:root {
${TokenSheetBuilder.#declarations(aliases, '')}
${TokenSheetBuilder.#declarations(literals, '')}

  /* Component corner sizes share the panel radius. */
  --radius: var(${PREFIX}-radius-panel);
}

@theme inline {
${TokenSheetBuilder.#declarations(themeMappings, '')}

  --font-sans: var(${PREFIX}-font-ui);
  --font-mono: var(${PREFIX}-font-mono);

${TokenSheetBuilder.#declarations(
    Object.keys(this.#tokens.type).map((key) => [`  --text-${key}`, `var(${PREFIX}-type-${key})`]),
    '',
)}

  --radius-sm: max(2px, calc(var(--radius) - 4px));
  --radius-md: max(2px, calc(var(--radius) - 2px));
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) + 4px);
}
`;
    }
}

const tokens = JSON.parse(readFileSync(join(PACKAGE_ROOT, 'src/tokens.json'), 'utf8'));
const catalog = JSON.parse(readFileSync(join(PACKAGE_ROOT, 'src/workspace-themes.json'), 'utf8'));
const builder = new TokenSheetBuilder(tokens, catalog);

const outputs = [
    ['tokens.css', builder.buildTokensCss()],
    ['theme.css', builder.buildThemeCss()],
];

const shouldCheck = process.argv.includes('--check');
let drifted = false;

for (const [filename, contents] of outputs) {
    const path = join(PACKAGE_ROOT, filename);
    if (shouldCheck) {
        let current = null;
        try {
            current = readFileSync(path, 'utf8');
        } catch {
            current = null;
        }
        if (current !== contents) {
            console.error(
                `tokens: ${filename} is out of date; run 'pnpm --filter @clipmill/tokens build'`,
            );
            drifted = true;
        }
    } else {
        writeFileSync(path, contents);
        console.log(`tokens: wrote ${filename}`);
    }
}

if (drifted) {
    process.exit(1);
}
if (shouldCheck) {
    console.log('tokens: OK (generated CSS matches tokens.json)');
}
