# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clipmill/time/v1/time.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'clipmill/time/v1/time.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63lipmill/time/v1/time.proto\x12\x10\x63lipmill.time.v1\".\n\x08Timebase\x12\x10\n\x03num\x18\x01 \x01(\x03R\x03num\x12\x10\n\x03\x64\x65n\x18\x02 \x01(\x03R\x03\x64\x65n\"\x1d\n\x05Ticks\x12\x14\n\x05ticks\x18\x01 \x01(\x03R\x05ticks\"H\n\x08Interval\x12\x1f\n\x0bstart_ticks\x18\x01 \x01(\x03R\nstartTicks\x12\x1b\n\tend_ticks\x18\x02 \x01(\x03R\x08\x65ndTicksb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clipmill.time.v1.time_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIMEBASE']._serialized_start=49
  _globals['_TIMEBASE']._serialized_end=95
  _globals['_TICKS']._serialized_start=97
  _globals['_TICKS']._serialized_end=126
  _globals['_INTERVAL']._serialized_start=128
  _globals['_INTERVAL']._serialized_end=200
# @@protoc_insertion_point(module_scope)
