#!/usr/bin/env python3
"""Generate desktop icons and SVG assets from the shared ClipMill mark.

Run after pnpm install. Rasterization uses the workspace's pinned Tauri CLI.
"""

from __future__ import annotations

import json
import shutil
import struct
import subprocess
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
DESKTOP = HERE.parents[1]


def main() -> None:
    mark = json.loads((DESKTOP / "src/brand/mark.json").read_text())
    sails = "\n".join(
        f'<path d="{mark["blade"]}" transform="rotate({angle} 50 50)" '
        'fill-rule="evenodd" />'
        for angle in (0, 90, 180, 270)
    )
    shapes = f'{sails}\n<circle cx="50" cy="50" r="{mark["hubRadius"]}" />'
    public = DESKTOP / "public"
    (public / "brand-mark.svg").write_text(
        "<!-- Generated by src-tauri/icons/generate.py. -->\n"
        '<svg xmlns="http://www.w3.org/2000/svg" '
        f'viewBox="{mark["viewBox"]}" fill="currentColor">\n{shapes}\n</svg>\n'
    )
    (public / "brand-icon.svg").write_text(
        "<!-- Generated by src-tauri/icons/generate.py. -->\n"
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">\n'
        '<rect width="64" height="64" rx="15" fill="#f3f1e9" />\n'
        f'<g fill="#242720" transform="translate(5 5) scale(.54)">\n{shapes}\n</g>\n'
        "</svg>\n"
    )
    source = HERE / "app-icon.svg"
    source.write_text(
        "<!-- Generated by generate.py. -->\n"
        '<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" '
        'viewBox="0 0 1024 1024">\n'
        '<rect x="80" y="80" width="864" height="864" rx="196" '
        'fill="#f3f1e9" stroke="#dbdcd4" stroke-width="2" />\n'
        f'<g transform="translate(162 162) scale(7)" fill="#242720">\n{shapes}\n</g>\n'
        "</svg>\n"
    )
    # Keep only desktop outputs; Tauri also generates mobile/store variants.
    with tempfile.TemporaryDirectory(prefix="clipmill-icons-") as generated:
        subprocess.run(
            ["pnpm", "exec", "tauri", "icon", str(source), "--output", generated],
            cwd=DESKTOP,
            check=True,
        )
        for name in (
            "32x32.png",
            "128x128.png",
            "128x128@2x.png",
            "icon.png",
            "icon.icns",
            "icon.ico",
        ):
            shutil.copyfile(Path(generated) / name, HERE / name)
    # Tauri emits ICNS representations in arbitrary order; normalize the container.
    icns = HERE / "icon.icns"
    data = icns.read_bytes()
    chunks = []
    offset = 8
    while offset < len(data):
        size = struct.unpack_from(">I", data, offset + 4)[0]
        chunks.append(data[offset : offset + size])
        offset += size
    icns.write_bytes(data[:8] + b"".join(sorted(chunks)))
    print("Generated ClipMill SVG, PNG, ICNS and ICO assets.")


if __name__ == "__main__":
    main()
